package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"pt-br\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"UTF-8\" />\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\" />\n");
      out.write("    <title>\n");
      out.write("      Tailwind Starter Template - Landing Page Template: Tailwind Toolbox\n");
      out.write("    </title>\n");
      out.write("    <meta name=\"description\" content=\"Simple landind page\" />\n");
      out.write("    <meta name=\"keywords\" content=\"\" />\n");
      out.write("    <meta name=\"author\" content=\"\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css\"/>\n");
      out.write("    <!--Replace with your tailwind.css once created-->\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700\" rel=\"stylesheet\" />\n");
      out.write("    <!-- Define your gradient here - use online tools to find a gradient matching your branding-->\n");
      out.write("    <script src=\"mododark.js\"></script>\n");
      out.write("    <link rel=\"stylesheet\" href=\"nav.css\">\n");
      out.write("  </head>\n");
      out.write("  <body class=\"leading-normal tracking-normal text-white gradient\" style=\"font-family: 'Source Sans Pro', sans-serif;\">\n");
      out.write("    <!--Nav-->\n");
      out.write("    \n");
      out.write("     \n");
      out.write("    <nav class=\"bg-white border-gray-300 dark:bg-gray-900 w-full\">\n");
      out.write("        <div class=\"flex flex-wrap w-full  h-15 justify-between tamanho\">\n");
      out.write("          <div class=\"flex ml-4 tirarmargin\">\n");
      out.write("          <a href=\"/src/home.html\" class=\"flex items-start\">\n");
      out.write("            <img src=\"/src/log.png\" class=\"  mr-3 mt-1 h-12 w-12 logo\" alt=\"HRB Kids Logo\" />\n");
      out.write("        </a>\n");
      out.write("    \n");
      out.write("        <!-- escolha do idioma -->\n");
      out.write("  \n");
      out.write("        <!-- TELAS -->\n");
      out.write("        <div class=\"navcontainer\">\n");
      out.write("        <div class=\"hidden  navbarmobile w-full md:flex md:w-auto md:order-1\" id=\"navbar-sticky\">\n");
      out.write("          <ul class=\"flex flex-col p-4 mt-4 optionsnav rounded-lg md:flex-row md:space-x-8 md:mt-0  md:font-medium md:border-0\">\n");
      out.write("            <li>\n");
      out.write("              <a href=\"/src/Produtos.html\" id=\"Produtos\" class=\"block py-2 pr-4 pl-3 text-gray-700 rounded 0 md:hover:bg-transparent  md:p-0 dark:text-gray-400 md:dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700\" aria-current=\"page\">Produtos</a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("              <a href=\"/src/Clientes.html\" id=\"Clientes\" class=\"block py-2 pr-4 pl-3 text-gray-700 rounded  md:hover:bg-transparent  md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700\">Clientes</a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("              <a href=\"/src/Avaliacao.html\" id=\"Avaliacao\" class=\"block py-2 pr-4 pl-3 text-gray-700 rounded  md:hover:bg-transparent md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700\">Avaliação</a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("              <button class=\"login rounded-lg pl-3 p-1 pr-3\">\n");
      out.write("                <a href=\"/src/Clientes.html\" id=\"login\" class=\"block text-gray-700 md:text-white dark:text-gray-400 md:dark:text-white  rounded md:p-0 \">Entrar</a>\n");
      out.write("              </button>\n");
      out.write("            </li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("      <div class=\"ml-5 relative margintop\">\n");
      out.write("      <div class=\"flex md:order-2 tirarmargin mt-2 mr-2  md:font-medium\">\n");
      out.write("        <button id=\"theme-toggle\" type=\"button\" class=\"mr-4 tirarmargin text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg  p-2.5\">\n");
      out.write("          <svg id=\"theme-toggle-dark-icon\" class=\"hidden w-5 h-5\" fill=\"currentColor\" viewBox=\"0 0 20 20\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z\"></path></svg>\n");
      out.write("          <svg id=\"theme-toggle-light-icon\" class=\"hidden w-5 h-5\" fill=\"currentColor\" viewBox=\"0 0 20 20\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z\" fill-rule=\"evenodd\" clip-rule=\"evenodd\"></path></svg>\n");
      out.write("      </button>\n");
      out.write("      <p class=\"idiomatext mt-1 dark:text-gray-400\">Idioma:</p>\n");
      out.write("        <button type=\"button\" data-dropdown-toggle=\"language-dropdown-menu\" class=\"font-semibold inline-flex justify-center idioma p-2  text-gray-500 rounded cursor-pointer hover:text-gray-900 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white\">\n");
      out.write("          <img class=\"w-5 h-5 rounded-full \" aria-hidden=\"true\" src=\"/src/img/bandeira-do-brasil.png\"/>\n");
      out.write("        </button>\n");
      out.write("        <button type=\"button\" data-dropdown-toggle=\"language-dropdown-menu\" class=\"font-semibold inline-flex justify-center idioma p-2  text-gray-500 rounded cursor-pointer hover:text-gray-900 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white\">\n");
      out.write("          <img class=\" w-5 h-5 rounded-full \" aria-hidden=\"true\" src=\"/src/img/bandeira-eua.png\"/>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"flex md:order-2\">\n");
      out.write("          <button data-collapse-toggle=\"navbar-sticky\" type=\"button\" class=\"inline-flex items-center p-2  text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600\" aria-controls=\"navbar-sticky\" aria-expanded=\"false\">\n");
      out.write("            <span class=\"sr-only\">Open main menu</span>\n");
      out.write("            <svg class=\"w-6 h-6\" aria-hidden=\"true\" fill=\"currentColor\" viewBox=\"0 0 20 20\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" d=\"M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z\" clip-rule=\"evenodd\"></path></svg>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("     \n");
      out.write("  </div>\n");
      out.write("  </div>\n");
      out.write("      </nav>\n");
      out.write("      <style>\n");
      out.write("    .gradient {\n");
      out.write("      background: linear-gradient(90deg, #0bc889 0%, #8af8d4 100%);\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("  \n");
      out.write("    <!--Hero-->\n");
      out.write("    <div class=\"pt-8 div\">\n");
      out.write("      <div class=\" pl-3 mx-auto flex flex-wrap flex-col md:flex-row items-center\">\n");
      out.write("        <!--Left Col-->\n");
      out.write("        <div class=\"flex flex-col width md:w-2/5 justify-center items-start text-center md:text-left\">\n");
      out.write("          <p class=\"uppercase tracking-loose w-full\">What business are you?</p>\n");
      out.write("          <h1 class=\"my-4 text-5xl font-bold leading-tight\">\n");
      out.write("            Sistema ERP Brechozinho\n");
      out.write("          </h1>\n");
      out.write("          <p class=\"leading-normal text-2xl mb-8\">\n");
      out.write("            Cadastre clientes, produtos e automatize o processo de avaliação! \n");
      out.write("          </p>\n");
      out.write("          <button class=\"mx-auto lg:mx-0 hover:underline bg-white text-gray-800 font-bold rounded-full my-6 py-4 px-8 shadow-lg focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out\">\n");
      out.write("            Entrar\n");
      out.write("          </button>\n");
      out.write("        </div>\n");
      out.write("        <!--Right Col-->\n");
      out.write("        <div class=\"img1 md:w-3/5 text-center\">\n");
      out.write("          <img class=\"img\" src=\"/imagens/girl.png\" />\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <section class=\"bg-white border-b py-8\">\n");
      out.write("      <div class=\"container max-w-5xl mx-auto m-8\">\n");
      out.write("        <h2 class=\"w-full my-2 text-5xl font-bold leading-tight text-center text-gray-800\">\n");
      out.write("          Sistema de Gestão\n");
      out.write("        </h2>\n");
      out.write("        <div class=\"w-full mb-4 mt-5\">\n");
      out.write("          <div class=\"h-1 mx-auto gradient w-64 opacity-25 my-0 py-0 rounded-t\"></div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"flex flex-wrap\">\n");
      out.write("          <div class=\"w-5/6 sm:w-1/2 md:py-24\tp-6\">\n");
      out.write("            <h3 class=\"text-3xl text-gray-800 md:px-8 font-bold leading-none mt-4 mb-3\">\n");
      out.write("              Solução Personalizada\n");
      out.write("            </h3>\n");
      out.write("            <p class=\"text-gray-600 md:px-8 \">\n");
      out.write("             Software desenvolvido pensando em todas as necessidades do brechozinho! Cadastre clientes, produtos, avaliações e gerencie o valor do Crédito gerado!\n");
      out.write("              <br />\n");
      out.write("              <br/>\n");
      out.write("            </p>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"w-full sm:w-1/2 p-6 items-center\t\">\n");
      out.write("            <img src=\"/imagens/avaliacoes.svg\">\n");
      out.write("           \n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"flex flex-wrap flex-col-reverse sm:flex-row\">\n");
      out.write("          <div class=\"w-full sm:w-1/2  mt-6\">\n");
      out.write("            <img src=\"/imagens/avaliar.svg\">\n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("          <div class=\"w-full sm:w-1/2 p-6 mt-6\">\n");
      out.write("            <div class=\"align-middle\">\n");
      out.write("              <h3 class=\"text-3xl text-gray-800 font-bold leading-none mb-3\">\n");
      out.write("                Praticidade\n");
      out.write("              </h3>\n");
      out.write("              <p class=\"text-gray-600 mb-8\">\n");
      out.write("                Chega de planilhas confusas! Agora com nosso sistema todas as informações necessárias do brechozinho ficam em um\n");
      out.write("                único lugar, com muita praticidade, organização e eficiência!\n");
      out.write("                <br />\n");
      out.write("                <br />\n");
      out.write("                \n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("    <section class=\"bg-white border-b py-8\">\n");
      out.write("      <div class=\"container containerwidth mx-auto flex flex-wrap pt-4 pb-12\">\n");
      out.write("        <h2 class=\"w-full my-2 text-5xl font-bold leading-tight text-center text-gray-800\">\n");
      out.write("          Acesso rápido\n");
      out.write("        </h2>\n");
      out.write("        <div class=\"w-full mb-4\">\n");
      out.write("          <div class=\"h-1 mx-auto gradient w-64 opacity-25 my-0 py-0 rounded-t\"></div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"w-full md:w-1/3 p-6 flex flex-col flex-grow flex-shrink\">\n");
      out.write("          <div class=\"flex-1 bg-white rounded-t rounded-b-none overflow-hidden shadow\">\n");
      out.write("              <div class=\" text-center w-full mt-5 font-bold text-xl text-gray-800 px-6\">\n");
      out.write("                Clientes\n");
      out.write("              </div>\n");
      out.write("              <p class=\" text-center text-gray-800 text-base px-6 mb-5 mt-3\">\n");
      out.write("                Consulte/cadastre clientes em nosso sistema! Através desse cadastro fica muito fácil entrar em contato com o cliente               </p>\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow \">\n");
      out.write("            <div class=\"flex items-center justify-center\">\n");
      out.write("              <button class=\"mx-auto lg:mx-0 hover:underline gradient text-white font-bold rounded-full my-6 py-4 px-8 shadow-lg focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out\">\n");
      out.write("                Clique aqui\n");
      out.write("              </button>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"w-full md:w-1/3 p-6 flex flex-col flex-grow flex-shrink\">\n");
      out.write("          <div class=\"flex-1 bg-white rounded-t rounded-b-none overflow-hidden shadow\">\n");
      out.write("            <a href=\"#\" class=\"flex flex-wrap no-underline hover:no-underline\">\n");
      out.write("              <p class=\"w-full text-gray-600 text-xs md:text-sm px-6\">\n");
      out.write("                xGETTING STARTED\n");
      out.write("              </p>\n");
      out.write("              <div class=\"w-full font-bold text-xl text-gray-800 px-6\">\n");
      out.write("                Avaliação\n");
      out.write("              </div>\n");
      out.write("              <p class=\"text-gray-800 text-base px-6 mb-5\">\n");
      out.write("                Consulte/cadastre avaliações! Tenha total controle sobre a sacola, tenha acesso a informações como lucro líquido e valor do crédito gerado!\n");
      out.write("              </p>\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow\">\n");
      out.write("            <div class=\"flex items-center justify-center\">\n");
      out.write("              <button class=\"mx-auto lg:mx-0 hover:underline gradient text-white font-bold rounded-full my-6 py-4 px-8 shadow-lg focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out\">\n");
      out.write("                Action\n");
      out.write("              </button>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"w-full md:w-1/3 p-6 flex flex-col flex-grow flex-shrink\">\n");
      out.write("          <div class=\"flex-1 bg-white rounded-t rounded-b-none overflow-hidden shadow\">\n");
      out.write("            <a href=\"#\" class=\"flex flex-wrap no-underline hover:no-underline\">\n");
      out.write("              <p class=\"w-full text-gray-600 text-xs md:text-sm px-6\">\n");
      out.write("                xGETTING STARTED\n");
      out.write("              </p>\n");
      out.write("              <div class=\"w-full font-bold text-xl text-gray-800 px-6\">\n");
      out.write("                Lorem ipsum dolor sit amet.\n");
      out.write("              </div>\n");
      out.write("              <p class=\"text-gray-800 text-base px-6 mb-5\">\n");
      out.write("                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at ipsum eu nunc commodo posuere et sit amet ligula.\n");
      out.write("              </p>\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow \">\n");
      out.write("            <div class=\"flex items-center justify-center\">\n");
      out.write("              <button class=\"mx-auto lg:mx-0 hover:underline gradient text-white font-bold rounded-full my-6 py-4 px-8 shadow-lg focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out\">\n");
      out.write("                Action\n");
      out.write("              </button>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("    \n");
      out.write("   \n");
      out.write("   \n");
      out.write("    <!-- jQuery if you need it\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write("  -->\n");
      out.write("    <style>\n");
      out.write("      .gradient {\n");
      out.write("        background: linear-gradient(90deg, #0bc889 0%, #8af8d4 100%);\n");
      out.write("      }\n");
      out.write(" .img1{\n");
      out.write("    margin-top: 0;\n");
      out.write("  margin-top: 5%;}\n");
      out.write("\n");
      out.write(".div{\n");
      out.write("      width: 80%;\n");
      out.write("      margin-left: 6%;\n");
      out.write("\n");
      out.write("    }\n");
      out.write("    /* .containerwidth{\n");
      out.write("      width: 80%;\n");
      out.write("      height: 60%;\n");
      out.write("    } */\n");
      out.write("   @media (max-width:767px){\n");
      out.write("    .div{\n");
      out.write("      text-align: center;\n");
      out.write("    }\n");
      out.write("    .img1{\n");
      out.write("    margin-top: 0;\n");
      out.write("  text-align: center;}\n");
      out.write("\n");
      out.write(" .img{\n");
      out.write("  width: 90%;\n");
      out.write("  margin-left:6%;\n");
      out.write(" }\n");
      out.write("\n");
      out.write("   }\n");
      out.write("   @media (max-width:1190px){\n");
      out.write("    .div{\n");
      out.write("      height: 75%;\n");
      out.write("      width: 90%;\n");
      out.write("    }\n");
      out.write("    .img1{\n");
      out.write("      margin-top:5%\n");
      out.write("    }\n");
      out.write("   }\n");
      out.write("    @media (min-width:1200px){\n");
      out.write("      .div{\n");
      out.write("        width: 60%;\n");
      out.write("        margin-left: 15%;\n");
      out.write("      }\n");
      out.write("      .img{\n");
      out.write("        margin-left: 20%;\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write(" style>\n");
      out.write("  .color{\n");
      out.write("    color:#0bde97;\n");
      out.write("  }\n");
      out.write("  a:hover{\n");
      out.write("    color:#0bc889;\n");
      out.write("  }\n");
      out.write("   \n");
      out.write("    @media (max-width:431px){\n");
      out.write("      .optionsnav{\n");
      out.write("        padding:0rem;\n");
      out.write("        margin:20%\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("@media (max-width:767px){\n");
      out.write("  .idiomatext{\n");
      out.write("    display: none;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write(" @media(min-width:768px){\n");
      out.write("  nav{\n");
      out.write("    width:85%\n");
      out.write("  }\n");
      out.write("  body{\n");
      out.write("    width: 100%;\n");
      out.write("    display:block;\n");
      out.write("   }\n");
      out.write("    .login{\n");
      out.write("    background-color: #0bde97;\n");
      out.write("    margin-top: -7%;\n");
      out.write("    \n");
      out.write("  }\n");
      out.write("  .login:hover{\n");
      out.write("    background-color: #0bc889;\n");
      out.write("  }\n");
      out.write("  .login a{\n");
      out.write("    color:white;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("@media (max-width:399px){\n");
      out.write("  .tamanho{\n");
      out.write("    flex-wrap: nowrap;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("     \n");
      out.write("      \n");
      out.write("    </style>\n");
      out.write("    <script>\n");
      out.write("    alert(teste);\n");
      out.write("\n");
      out.write("////////////////\n");
      out.write("//TEMA DARK\n");
      out.write("// On page load or when changing themes, best to add inline in `head` to avoid FOUC\n");
      out.write("if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {\n");
      out.write("   document.documentElement.classList.add('dark');\n");
      out.write("} else {\n");
      out.write("   document.documentElement.classList.remove('dark')\n");
      out.write("}\n");
      out.write("\n");
      out.write("var themeToggleDarkIcon = document.getElementById('theme-toggle-dark-icon');\n");
      out.write("var themeToggleLightIcon = document.getElementById('theme-toggle-light-icon');\n");
      out.write("\n");
      out.write("//Change the icons inside the button based on previous settings\n");
      out.write("if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {\n");
      out.write(" themeToggleLightIcon.classList.remove('hidden');\n");
      out.write("} else {\n");
      out.write(" themeToggleDarkIcon.classList.remove('hidden');\n");
      out.write("}\n");
      out.write("\n");
      out.write("var themeToggleBtn = document.getElementById('theme-toggle');\n");
      out.write("\n");
      out.write("themeToggleBtn.addEventListener('click', function() {\n");
      out.write("\n");
      out.write(" // toggle icons inside button\n");
      out.write(" themeToggleDarkIcon.classList.toggle('hidden');\n");
      out.write(" themeToggleLightIcon.classList.toggle('hidden');\n");
      out.write("\n");
      out.write(" // if set via local storage previously\n");
      out.write(" if (localStorage.getItem('color-theme')) {\n");
      out.write("     if (localStorage.getItem('color-theme') === 'light') {\n");
      out.write("         document.documentElement.classList.add('dark');\n");
      out.write("         localStorage.setItem('color-theme', 'dark');\n");
      out.write("     } else {\n");
      out.write("         document.documentElement.classList.remove('dark');\n");
      out.write("         localStorage.setItem('color-theme', 'light');\n");
      out.write("     }\n");
      out.write("\n");
      out.write(" // if NOT set via local storage previously\n");
      out.write(" } else {\n");
      out.write("     if (document.documentElement.classList.contains('dark')) {\n");
      out.write("         document.documentElement.classList.remove('dark');\n");
      out.write("         localStorage.setItem('color-theme', 'light');\n");
      out.write("     } else {\n");
      out.write("         document.documentElement.classList.add('dark');\n");
      out.write("         localStorage.setItem('color-theme', 'dark');\n");
      out.write("     }\n");
      out.write(" }\n");
      out.write("})\n");
      out.write("\n");
      out.write("</script>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layoutrodape.jsp", out, false);
      out.write("\n");
      out.write("     \n");
      out.write("  </body>\n");
      out.write("</html>\n");
      out.write("\t\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
